version: '3.8'

services:
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: /root/.acme.sh/quori.rachidjeffali.com_ecc
        target: /certs
    volumes_from:
      - fpm
    depends_on:
      - fpm

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rachidj
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  fpm:
    ports:
      - '8000:8000'
    build:
      context: .
      dockerfile: Dockerfile.fpm
    volumes:
      - type: bind
        target: /app
        source: .
    depends_on:
      - mysql

  node:
    ports:
      - '8080:8080'
    build: 
      context: .
      dockerfile: Dockerfile.encore.prod
    volumes:
      - type: volume
        target: /app/node_modules
      - type: bind
        target: /app
        source: .

volumes:
  db:
  tls: